import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Michal's D&D Ruleset",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main
          className={`grid w-full min-h-screen place-items-center bg-gray-100 p-4`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
