// app/layout.tsx
import type { Metadata } from "next";
import "./globals.scss";
import { QueryProvider } from "./providers";
import { PreviewGrid } from "@/components/layout/gridLayout";

export const metadata: Metadata = {
  title: "Michal's D&D Ruleset",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <PreviewGrid />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
