import Header from "@/components/header";
import Navbar from "@/components/navbar";
import { Grid, GridItem, Box, Text } from "@chakra-ui/react";
import Head from "next/head";

const MainLayout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>D&D Starter Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box w="80%" mx="auto">
        <Grid
          templateAreas={{
            base: `"header"
                  "main"
                  "footer"`,

            lg: `"header header"
                  "nav main"
                  "footer footer"`,
          }}
          gridTemplateColumns={{ base: "100%", lg: "250px 1fr" }}
          gap="1"
        >
          <GridItem pl="2" area={"header"}>
            <Header />
          </GridItem>
          <GridItem
            pl="2"
            pr="5"
            area={"nav"}
            display={{ base: "none", lg: "block" }}
          >
            <Navbar />
          </GridItem>
          <GridItem px="5" area={"main"} maxW={{ base: "80vw", lg: "65vw" }}>
            <Box as="main">{children}</Box>
          </GridItem>
          <GridItem pl="2" py={12} area={"footer"}>
            <Text textAlign="center">
              Hi, I am a footer, please don&apos;t mind me, Michael needs me to
              see if everything works as it should :)
            </Text>
          </GridItem>
        </Grid>
      </Box>
    </>
  );
};

export default MainLayout;
